export const DEFAULT_CATEGORIES = [
  { name: 'Alimentação', icon: 'UtensilsCrossed', color: '#ef4444' },
  { name: 'Transporte', icon: 'Car', color: '#f97316' },
  { name: 'Moradia', icon: 'Home', color: '#eab308' },
  { name: 'Mercado', icon: 'ShoppingCart', color: '#22c55e' },
  { name: 'Saúde', icon: 'HeartPulse', color: '#ec4899' },
  { name: 'Cuidados pessoais', icon: 'Scissors', color: '#a855f7' },
  { name: 'Lazer', icon: 'Music', color: '#8b5cf6' },
  { name: 'Educação', icon: 'GraduationCap', color: '#3b82f6' },
  { name: 'Compras', icon: 'ShoppingBag', color: '#f59e0b' },
  { name: 'Assinaturas', icon: 'Repeat', color: '#6366f1' },
  { name: 'Casa', icon: 'Home', color: '#06b6d4' },
  { name: 'Pets', icon: 'PawPrint', color: '#f97316' },
  { name: 'Viagens', icon: 'Plane', color: '#3b82f6' },
  { name: 'Impostos', icon: 'FileText', color: '#f59e0b' },
  { name: 'Salário', icon: 'Wallet', color: '#22c55e' },
  { name: 'Freelance', icon: 'Briefcase', color: '#14b8a6' },
  { name: 'Investimentos', icon: 'TrendingUp', color: '#10b981' },
  { name: 'Venda', icon: 'BadgeDollarSign', color: '#14b8a6' },
  { name: 'Outros', icon: 'Sparkles', color: '#64748b' },
];
